#指定 j2cache-spring-boot2-starter 配置文件位置
j2cache:
 config-location: /j2cache-${spring.cloud.config.profile}.properties
spring:
  jackson:
    time-zone: GMT+8 #调整到中国时区
    date-format: yyyy-MM-dd HH:mm:ss

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS











