spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: http://120.79.216.43:81/root/dp-distribution-config.git # 配置git仓库的地址
          search-paths: '{application}' # git仓库地址下的相对地址，可以配置多个，用,分割。 application作为一个占位符，不同的项目进来，可以匹配到不同的文件夹下面去寻找对应的配置文件
          username: root
          password: Dpof2018
          #uri: https://github.com/MinLancer/springcloudstudy2
    bus:
     enabled: true
     trace:
       enabled: true
  rabbitmq:
    host: rabbitmq
    port: 5672
    virtual-host: dp-distribution
    username: dpRabbitMq
    password: DpMq123456
  #访问配置中心服务需要携带账号密码
  security:
    user:
      name: lancer
      password: 111111
server:
  port: 12000
eureka:
  client:
    service-url:
      #启用账号密码验证时，格式 http://账号:密码@hostname:端口号/eureka
      defaultZone: http://lancer:123456@eureka-server:7000/eureka
       #没有启用账号密码验证时
#      defaultZone: http://localhost:7000/eureka/

management:
  endpoints:
    web:
      exposure:
        include: bus-refresh